# Site settings
title: snugg.ie
description: "Beep-boop. Beep-boop. Here is Evie Snuggle's (beta) site! &#127861;&nbsp;&#127800;"

unpublished: false

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://snugg.ie" # the base hostname & protocol for your site, e.g. http://example.com
